### ISSUE TITLE
A bug? - Applying initial UI patch for Config Server Security & Firewall and reloading. Please wait...

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1341]
I have Ubuntu 18.04 and latest Webmin, csf. Had some problems with firewall, so I pressed Reset all in csf settings and after automatic process I see all the time this error in never-ending loop:
![111](https://user-images.githubusercontent.com/7549566/57575049-1ecaa400-743b-11e9-88d7-03d8699ac2f5.jpg)

csf is disabled now, and I cannot go to csf settings, I uninstalled all again and installed back once again, and the problem still there.
![222](https://user-images.githubusercontent.com/7549566/57575119-bda3d000-743c-11e9-943a-79ef57225d41.jpg)

also I activated all below settings, and finally pressed: Reinstall csf
![333](https://user-images.githubusercontent.com/7549566/57575122-cf857300-743c-11e9-82f1-1778ef518378.jpg)

Is that related to the theme? any idea how to fix it?

**Comment by rostovtsev** [comment]
Yes, theme controls it.

However, this message should show once, until files are patched. 

At the moment I have one idea, why this could be happening. At first, did you force reload the theme?

Second, if above doesn't help, what if you delete `/etc/webmin/authentic-theme/csf.ui-introduced` file and again reload the page, does it help then?

I will take a closer look starting Monday.

**Comment by sz00gun** [comment]
Shocking! Thank you 
1st solution didn't help, however the second did!

Thx

**Comment by rostovtsev** [comment]
Okay, I will fix that.

**Comment by rostovtsev** [comment]
Okay, it's fix and now, reinstalling of ConfigServer Security & Firewall works just fine.

Thank you for reporting. :nerd_face:

**Comment by SuperCurro** [comment]
Hello I still have the same problem with ConfigServer Security & Firewall 13.04   and Authentic theme version | 19.38

I have tried all I have found about this type of problems in several threads and it doesnt work in my two servers with ubuntu 16.04.

With grey theme no problem at all.

Any idea?

**Comment by rostovtsev** [comment]
Do you mean CSF->Fix Common Problems->Reinstall?

I just tried it on Debian 9 and all seems to work just fine. CSF itself and reinstall as well.

What is not working? What browser are you using?

**Comment by SuperCurro** [comment]
I dont Reinstall... my CSF configuration is complex... If I reinstall can I use the same config file?

I tried in all web browsers (Chrome, Firefox, IE, etc).

**Comment by SuperCurro** [comment]
Ok, I did reinstall CSF and doesnt work, still reloading all the time the screen.

**Comment by rostovtsev** [comment]
The most possible problem, is that your theme not updated. Possible you need to hard reload the page by holding _Shift_ and clicking reload button at the browser, near the URL bar. Try incognito tab. I'm case the theme is updated you wouldn't have such issue.

**Comment by rostovtsev** [comment]
Try restarting Webmin as well. It looks like the cache issue.

**Comment by SuperCurro** [comment]
![image](https://user-images.githubusercontent.com/53261532/61819313-12a78d80-ae53-11e9-87e7-8746b648ed18.png)

I had no problem months ago, and every time a test something I restart the webmin. I also tested clear the web cache and surf from diferents web browsers.

![image](https://user-images.githubusercontent.com/53261532/61819548-8ba6e500-ae53-11e9-8787-873a8155c99d.png)

Is there any log where I can see what is happening?

Thanks for your support

**Comment by rostovtsev** [comment]
What is the output of `ls -lsa /etc/webmin/authentic-theme`?

**Comment by SuperCurro** [comment]
`curro@SERVIDOR1:~$ sudo ls -lsa /etc/webmin/authentic-theme
total 48
4 drwxr-xr-x   2 root root 4096 jul 24 16:16 .
4 drwxr-xr-x 121 root root 4096 jul 24 16:16 ..
4 -rw-r--r--   1 root root   90 jul 24 20:56 csf.body
4 -rw-r--r--   1 root root   47 jul 24 20:56 csf.bodytag
4 -rw-r--r--   1 root root   52 jul 24 20:56 csf.footer
4 -rw-r--r--   1 root root  617 jul 24 20:56 csf.header
4 -rw-r--r--   1 root root  896 jul 24 20:56 csf.htmltag
4 -rw-r--r--   1 root root    1 jul 24 16:16 csf.ui
4 -rw-r--r--   1 root root    1 dic 29  2016 csf.ui-introduced
4 -rw-r--r--   1 root root  578 oct  1  2016 favorites-root.json
4 -rw-r--r--   1 root root 3560 may 23 22:24 settings.js
4 -rw-r--r--   1 root root 2040 jul 24 16:15 settings-root
curro@SERVIDOR1:~$`

**Comment by rostovtsev** [comment]
Unfortunately I can not reproduce it on 3 of my different servers.

Try:

```
cd /etc/webmin/authentic-theme/
rm -f *csf*
```

**Comment by rostovtsev** [comment]
Okay, I could reproduce it with specific configuration.

You must make sure that:

```
cat /etc/csf/csf.conf  |grep STYLE_ 
```

Is set to:

```BASH
STYLE_CUSTOM = "1"
```

Yours is set to `0`;

**Comment by rostovtsev** [comment]
It's no longer a UI option.

**Comment by rostovtsev** [comment]
However, deleting mentioned files should've also worked just fine for you.

**Comment by SuperCurro** [comment]
> Unfortunately, I can not reproduce it on 3 of my different servers.
> 
> Try:
> 
> ```
> cd /etc/webmin/authentic-theme/
> rm -f *csf*
> ```

this doesnt work



> Okay, I could reproduce it with specific configuration.
> 
> You must make sure that:
> 
> ```
> cat /etc/csf/csf.conf  |grep STYLE_ 
> ```
> 
> Is set to:
> 
> ```shell
> STYLE_CUSTOM = "1"
> ```
> 
> Yours is set to `0`;

You are right mine is set to 0, I changed it to 1, but still doesnt work. still the same problem. I restarted webmin, clean cookies etc, the same infinite reload cycle.

**Comment by SuperCurro** [comment]
Now rebooting, just in case.

**Comment by SuperCurro** [comment]
Afeter reboot the same situation, but now with the problem of the CSF stop
![image](https://user-images.githubusercontent.com/53261532/61819313-12a78d80-ae53-11e9-87e7-8746b648ed18.png)

**Comment by rostovtsev** [comment]
What makes you think that it's running?

What is the output of:

```
pgrep lfd
```

and of:

```
service lfd status
```

**Comment by SuperCurro** [comment]
You are right, is rare, if I change the theme to grey it shows everything ok.

```
● lfd.service - ConfigServer Firewall & Security - lfd
   Loaded: loaded (/usr/lib/systemd/system/lfd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mié 2019-07-24 22:02:48 CEST; 16min ago
  Process: 3055 ExecStart=/usr/sbin/lfd (code=exited, status=1/FAILURE)

jul 24 22:02:48 SERVIDOR1 systemd[1]: Starting ConfigServer Firewall & Security - lfd...
jul 24 22:02:48 SERVIDOR1 lfd[3055]: csf and lfd have been disabled
jul 24 22:02:48 SERVIDOR1 systemd[1]: lfd.service: Control process exited, code=exited status=1
jul 24 22:02:48 SERVIDOR1 systemd[1]: Failed to start ConfigServer Firewall & Security - lfd.
jul 24 22:02:48 SERVIDOR1 systemd[1]: lfd.service: Unit entered failed state.
jul 24 22:02:48 SERVIDOR1 systemd[1]: lfd.service: Failed with result 'exit-code'.
```

the log of the start
```
-- Unit csf.service has finished shutting down.
Jul 24 22:20:51 SERVIDOR1 systemd[1]: Starting ConfigServer Firewall & Security - csf...
-- Subject: Unit csf.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit csf.service has begun starting up.
Jul 24 22:20:51 SERVIDOR1 csf[18728]: csf and lfd have been disabled, use 'csf -e' to enable
Jul 24 22:20:51 SERVIDOR1 systemd[1]: csf.service: Main process exited, code=exited, status=1/FAILURE
Jul 24 22:20:51 SERVIDOR1 systemd[1]: Failed to start ConfigServer Firewall & Security - csf.
-- Subject: Unit csf.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit csf.service has failed.
-- 
-- The result is failed.
Jul 24 22:20:51 SERVIDOR1 systemd[1]: csf.service: Unit entered failed state.
Jul 24 22:20:51 SERVIDOR1 systemd[1]: csf.service: Failed with result 'exit-code'.
Jul 24 22:21:30 SERVIDOR1 systemd[1]: Stopped ConfigServer Firewall & Security - csf.
-- Subject: Unit csf.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit csf.service has finished shutting down.
Jul 24 22:21:38 SERVIDOR1 systemd[1]: Starting ConfigServer Firewall & Security - csf...
-- Subject: Unit csf.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit csf.service has begun starting up.
Jul 24 22:21:38 SERVIDOR1 csf[21518]: csf and lfd have been disabled, use 'csf -e' to enable
Jul 24 22:21:38 SERVIDOR1 systemd[1]: csf.service: Main process exited, code=exited, status=1/FAILURE
Jul 24 22:21:38 SERVIDOR1 systemd[1]: Failed to start ConfigServer Firewall & Security - csf.
-- Subject: Unit csf.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit csf.service has failed.
-- 
-- The result is failed.
Jul 24 22:21:38 SERVIDOR1 systemd[1]: csf.service: Unit entered failed state.
Jul 24 22:21:38 SERVIDOR1 systemd[1]: csf.service: Failed with result 'exit-code'.
```

**Comment by rostovtsev** [comment]
It was nothing to do with the theme. Your `lfd` is not running.

Are you in test mode?

```
cat /etc/csf/csf.conf |grep TESTING
```

Outputs

```
TESTING = "1"
```

While should be set to `1`.

**Comment by SuperCurro** [comment]
Is not in testing... 
![image](https://user-images.githubusercontent.com/53261532/61826371-9157f700-ae62-11e9-9467-47349a39d952.png)

```
# lfd will not start while this is enabled
TESTING = "0"
```

**Comment by SuperCurro** [comment]
I have change the theme to grey and now

```
 service lfd status
● lfd.service - ConfigServer Firewall & Security - lfd
   Loaded: loaded (/usr/lib/systemd/system/lfd.service; enabled; vendor preset: enabled)
   Active: active (running) since mié 2019-07-24 22:25:58 CEST; 6min ago
  Process: 25197 ExecStart=/usr/sbin/lfd (code=exited, status=0/SUCCESS)
 Main PID: 25206 (lfd - sleeping)
   CGroup: /system.slice/lfd.service
           └─25206 lfd - sleepin

jul 24 22:25:58 SERVIDOR1 systemd[1]: Starting ConfigServer Firewall & Security - lfd...
jul 24 22:25:58 SERVIDOR1 systemd[1]: Started ConfigServer Firewall & Security - lfd.
```

**Comment by rostovtsev** [comment]
Look at the output that you posted yourself:


```BASH
lfd.service - ConfigServer Firewall & Security - lfd
   Loaded: loaded (/usr/lib/systemd/system/lfd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mié 2019-07-24 22:02:48 CEST; 16min ago
  Process: 3055 ExecStart=/usr/sbin/lfd (code=exited, status=1/FAILURE)
```

The status is: Active: **_failed_**.

**Comment by rostovtsev** [comment]
> I have change the theme to grey and now

It's wrong. Theme has nothing to do with it, I am sorry.

**Comment by SuperCurro** [comment]
If I change again to authentic theme

![image](https://user-images.githubusercontent.com/53261532/61826637-23f89600-ae63-11e9-9a59-cec234505d5c.png)

but still the same problem, reloading all the time when I click... on it.

**Comment by rostovtsev** [comment]
What is the output of:


```
whereis csf
```

Besides, is there a way I could login to the server and take a closer look?

**Comment by SuperCurro** [comment]
```
 whereis csf
csf: /usr/sbin/csf /etc/csf /usr/local/csf /usr/src/csf/csf.sh /usr/src/csf/csf.logignore /usr/src/csf/csf.c /usr/src/csf/csf.help /usr/src/csf/csf.rblconf /usr/src/csf/csf.fignore /usr/src/csf/csf.uidignore /usr/src/csf/csf.pignore /usr/src/csf/csf.rbls /usr/src/csf/csf.smtpauth /usr/src/csf/csf.conf /usr/src/csf/csf.syslogs /usr/src/csf/csf.dyndns /usr/src/csf/csf.resellers /usr/src/csf/csf.logfiles /usr/src/csf/csf.suignore /usr/src/csf/csf.blocklists /usr/src/csf/csf.cloudflare /usr/src/csf/csf.syslogusers /usr/src/csf/csf.mignore /usr/src/csf/csf.signore /usr/src/csf/csf /usr/src/csf/csf.sips /usr/src/csf/csf.deny /usr/src/csf/csf.rignore /usr/src/csf/csf.div /usr/src/csf/csf.ignore /usr/src/csf/csf.allow /usr/src/csf/csf.pl /usr/src/csf/csf.dirwatch /usr/src/csf/csf.service /usr/src/csf/csf.redirect
curro@SERVIDOR1:~$
```

Yes I can give you access, SSH or easier teamviewer

**Comment by rostovtsev** [comment]
I don't need SSH, Webmin preferably. I need to see what's happening.

You can send it using my website securely.

**Comment by rostovtsev** [comment]
..or

You can tar `/etc/webmin/authentic-theme` and `/etc/csf` and send it to me.

I will take a look.

**Comment by SuperCurro** [comment]
I found the problem!!! Is the theme language, in spanish doesnt work
![image](https://user-images.githubusercontent.com/53261532/61827587-3542a200-ae65-11e9-9631-321e4d085edd.png)

**Comment by rostovtsev** [comment]
You are right. I will check what is causing it.

**Comment by SuperCurro** [comment]
Thank You very much for your support. It seams the patch only works in english... very tricky

**Comment by rostovtsev** [comment]
Okay, it's fixed. There was internal bug that made new linebreaks in titles. It's fixed now.

Update to the latest dev version using theme configuration or hitting the hotkey to update.

**Comment by SuperCurro** [comment]
I try to update, but is still 19.38... in any case once you change to English and deleted the /etc/webmin/ files it works well even in spanish.

```
cd /etc/webmin/authentic-theme/
rm -f *csf*
```

**Comment by rostovtsev** [comment]
You don't need to delete anything, it would just worked.

**Comment by SuperCurro** [comment]
Yes, after the patch it would, but before the patch no, and I think the patch is still not available, at least I still have the same version 19.38

**Comment by rostovtsev** [comment]
Okay, update once more. The minor version will be displayed.

**Comment by SuperCurro** [comment]
Sorry, perhaps is my mistake. How I should update the theme?

**Comment by rostovtsev** [comment]
![image](https://user-images.githubusercontent.com/4426533/61873307-500d2900-aeee-11e9-9b86-528fa59186d2.png)

**Comment by SuperCurro** [comment]
Thanks, yes I did beta in one server and stable in the other, yesterday didn't work but today yes.

Thank you very much

**Comment by sz00gun** [comment]
Here we go again. The bug still here :(. Problem as above...

Theme version: 19.61

**Comment by iliarostovtsev** [comment]
> Here we go again. The bug still here :(. Problem as above...

I have just installed latest CSF 14.07 on my test Debian 10 and it seems to work. Can you try clearing browser's cache first and then theme's cache from theme's configuration (as displayed above)?

If not, do you have steps to reproduce an issue?

**Comment by sz00gun** [comment]
Sorted, I have done many other tasks, not sure what helped. Please try do this: csf- firewall profiles button, and try to use option: reset_to_defaults

That brakes in my case in Ubuntu

If it working on your end probably something bad on my end. At least I know how to fix it so don't worry about it.

**Comment by iliarostovtsev** [comment]
> Sorted, I have done many other tasks, not sure what helped. Please try do this: csf- firewall profiles button, and try to use option: reset_to_defaults

I could reproduce it. I'll check what can be done. Thanks!

**Comment by iliarostovtsev** [comment]
Fixed with latest commit, thanks!
